module.exports = [

  { period: 'morning (before meal)'},
  { period: 'morning (after meal)'},
  { period: 'morning|afternoon(before meal)' },
  { period: 'morning|afternoon(after meal)' },
  { period: 'morning|evening (before meal)'},
  { period: 'morning|evening (after meal)'},
  { period: 'morning(before meal)|before sleeping ' },
  { period: 'morning(after meal)|before sleeping ' },
  { period: 'morning|afternoon|evening (before meal)' },
  { period: 'morning|afternoon|evening (after meal)' },
  { period: 'morning|afternoon|evening|(before meal)|before sleeping' },
  { period: 'morning|afternoon|evening|(after meal)|before sleeping' },
  { period: 'afternoon (before meal)' },
  { period: 'afternoon (after meal)' },
  { period: 'afternoon|evening (before meal)' },
  { period: 'afternoon|evening (after meal)' },
  { period: 'afternoon (before meal)|before sleeping' },
  { period: 'afternoon (after meal)|before sleeping' },
  { period: 'afternoon|evening (before meal)|before sleeping'},
  { period: 'afternoon|evening (after meal)|before sleeping'},
  { period: 'evening (before meal)' },
  { period: 'evening (after meal)' },
  { period: 'evening(before meal)|before sleeping'},
  { period: 'evening(after meal)|before sleeping'}
];
